version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  test-ruby:
    docker:
      - image: cimg/ruby:3.1.0-node
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Install Node.js dependencies
          command: yarn install
      - run:
          name: Precompile Webpacker
          command: RAILS_ENV=test bundle exec rails webpacker:compile
      - run:
          name: Precompile assets
          command: RAILS_ENV=test bundle exec rails assets:precompile
      - run:
          name: Run RSpec tests
          command: bundle exec rspec
    executor:
workflows:
  build-and-test:
    jobs:
      - test-ruby
